### ISSUE TITLE
Distinguish nullable vs non-nullable types

### ISSUE THREAD

**Issue by jlw5** [mwildehahn/hack-graphql#21]
In graphql-js, the default is nullable
```
info: { type: GraphQLString },
```
and you have to specify non-null if you want that.
```
id: { type: new GraphQLNonNull(GraphQLString) },
```

I'm not sure if this is dictated by the GraphQL standard or not. In the hack implementation so far, it looks like all types are non-null.

**Comment by ianhoffman** [comment]
Was this not fixed by #14?

**Comment by admdikramr** [comment]
In our codebase in Hack we have found it difficult to represent truly non-nullable output types due to exception handling. If a method that appears to not return null throws, what would we do in the GraphQL request? For us, we return null and stick the exception into the errors payload. However, if the field is non-nullable, per the spec, the entire object gets nulled out, including several other fields on the object that might be just fine. The bubbles up to the point at which one exception can fail the whole query. There's an upside to that of course, but it kinda runs counter to the "be as stable as possible" philosophy.

**Comment by jjergus** [comment]
Yep #14 implements this, the description explains some of the options and my thinking about them.
